kind: pipeline
name: build-pipeline-afrimash-admin
type: docker

steps:
- name: build-publish
  image: plugins/docker
  settings:
    repo: akinoyedotun/afrimashadmin
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  image: docker
  commands:
    - docker login -u $USERNAME --password $PASSWORD
    - docker pull akinoyedotun/afrimashadmin
    - docker stop afrimashadmin_test || true 
    - docker rm afrimashadmin_test || true
    - docker run --rm -d -p 3030:3000 -e "REACT_APP_SKIP_PREFLIGHT_CHECK=true" -e "CHOKIDAR_USEPOLLING=true" --name afrimashadmin_test akinoyedotun/afrimashadmin
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
image_pull_secrets:
- dockerconfigjson
