kind: pipeline
name: build-pipeline-afrimash-admin
type: docker

steps:
- name: build-docker-image
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: Dockerfile.dev
    repo: akinoyedotun/afrimashadmin
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: publish
  image: plugins/docker
  settings:
    repo: akinoyedotun/afrimashadmin
    dockerfile: Dockerfile.dev
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: deploy
  image: docker
  environment:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  commands:
#    - echo $PASSWORD |docker login -u $USERNAME --password-stdin
    - docker pull akinoyedotun/afrimashadmin
    - docker run --rm -d -p 3030:3000 -e "REACT_APP_SKIP_PREFLIGHT_CHECK=true" -e "CHOKIDAR_USEPOLLING=true" --name afrimashadmin_test akinoyedotun/afrimashadmin
  volumes:
  - name: docker
    path: /var/run/docker.sock
  image_pull_secrets:
  - dockerconfig

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
image_pull_secrets:
- dockerconfig
