export const bankCodes = [
    { "code": "044", "name": "Access Bank Nigeria Plc" },
    { "code": "063", "name": "Diamond Bank Plc" },
    { "code": "050", "name": "Ecobank Nigeria" },
    { "code": "084", "name": "Enterprise Bank Plc" },
    { "code": "070", "name": "Fidelity Bank Plc" },
    { "code": "011", "name": "First Bank of Nigeria Plc" },
    { "code": "214", "name": "First City Monument Bank" },
    { "code": "058", "name": "Guaranty Trust Bank Plc" },
    { "code": "030", "name": "Heritage Banking Company Ltd" },
    { "code": "301", "name": "Jaiz Bank" },
    { "code": "082", "name": "Keystone Bank Ltd" },
    { "code": "014", "name": "Mainstreet Bank Plc" },
    { "code": "076", "name": "Skye Bank Plc" },
    { "code": "039", "name": "Stanbic IBTC Plc" },
    { "code": "232", "name": "Sterling Bank Plc" },
    { "code": "032", "name": "Union Bank Nigeria Plc" },
    { "code": "033", "name": "United Bank for Africa Plc" },
    { "code": "215", "name": "Unity Bank Plc" },
    { "code": "035", "name": "WEMA Bank Plc" },
    { "code": "057", "name": "Zenith Bank International" },
]