export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara"
];

export const statesWithIds = [
  { "id": "1", "name": "Abia" },
  { "id": "2", "name": "Adamawa" },
  { "id": "3", "name": "Akwa Ibom" },
  { "id": "4", "name": "Anambra" },
  { "id": "5", "name": "Bauchi" },
  { "id": "6", "name": "Bayelsa" },
  { "id": "7", "name": "Benue" },
  { "id": "8", "name": "Borno" },
  { "id": "9", "name": "Cross River" },
  { "id": "10", "name": "Delta" },
  { "id": "11", "name": "Ebonyi" },
  { "id": "12", "name": "Edo" },
  { "id": "13", "name": "Ekiti" },
  { "id": "14", "name": "Enugu" },
  { "id": "15", "name": "FCT - Abuja" },
  { "id": "16", "name": "Gombe" },
  { "id": "17", "name": "Imo" },
  { "id": "18", "name": "Jigawa" },
  { "id": "19", "name": "Kaduna" },
  { "id": "20", "name": "Kano" },
  { "id": "21", "name": "Katsina" },
  { "id": "22", "name": "Kebbi" },
  { "id": "23", "name": "Kogi" },
  { "id": "24", "name": "Kwara" },
  { "id": "25", "name": "Lagos" },
  { "id": "26", "name": "Nasarawa" },
  { "id": "27", "name": "Niger" },
  { "id": "28", "name": "Ogun" },
  { "id": "29", "name": "Ondo" },
  { "id": "30", "name": "Osun" },
  { "id": "31", "name": "Oyo" },
  { "id": "32", "name": "Plateau" },
  { "id": "33", "name": "Rivers" },
  { "id": "34", "name": "Sokoto" },
  { "id": "35", "name": "Taraba" },
  { "id": "36", "name": "Yobe" },
  { "id": "37", "name": "Zamfara" }
]
